# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cnum', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('si', models.CharField(max_length=15, verbose_name='si')),
                ('gu', models.CharField(blank=True, max_length=15, null=True, verbose_name='gu')),
                ('dong', models.CharField(blank=True, max_length=15, null=True, verbose_name='dong')),
            ],
        ),
        migrations.CreateModel(
            name='Emer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(verbose_name='mid')),
                ('mname', models.CharField(max_length=20, verbose_name='mname')),
                ('mtel', models.CharField(max_length=15, verbose_name='mtel')),
                ('madd', models.CharField(max_length=500, verbose_name='madd')),
                ('cnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emer.City')),
            ],
            options={
                'verbose_name': 'emer',
                'verbose_name_plural': 'emers',
                'db_table': 'emer_emers',
                'ordering': ('id',),
            },
        ),
    ]
